services:
  dockerproxy:
    image: ghcr.io/wollomatic/socket-proxy:1.11.0
    restart: unless-stopped
    user: "65534:281"
    mem_limit: 64M
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=info'
      - '-listenip=0.0.0.0'
      - '-allowfrom=dozzle'
      - '-allowGET=/v1\..{1,2}/(info|events|containers/.*)|/_ping'
      - '-allowHEAD=/_ping'
      - '-allowbindmountfrom=/var/log,/tmp'
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
      - '-shutdowngracetime=5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet 


  dozzle:
    image: amir20/dozzle:v9.0.3
    container_name: dozzle
    depends_on:
      - dockerproxy
    volumes:
      - ${APPDATA_PATH}/dozzle:/data
    environment:
      - DOZZLE_REMOTE_HOST=tcp://dockerproxy:2375
      - DOZZLE_AUTH_PROVIDER=forward-proxy
      - DOZZLE_NO_ANALYTICS=true
    networks:
      - proxy
      - docker-proxynet
    env_file: .env
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.tls: true
      traefik.http.routers.dozzle.tls.certresolver: letsencrypt
      traefik.http.routers.dozzle.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.dozzle.entrypoints: websecure
      traefik.http.routers.dozzle.middlewares: tinyauth

      tinyauth.apps.dozzle.config.domain: ${SERVICE_URL}
      tinyauth.apps.dozzle.oauth.groups: admin

      glance.name: Dozzle
      glance.icon: sh:dozzle
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/dozzle.png
      net.unraid.docker.webui: https://${SERVICE_URL}
    restart: unless-stopped
    
networks:
  proxy:
    external: true
  docker-proxynet:
    driver: bridge
    internal: true
