services:
  airconnect:
    network_mode: host
    image: 1activegeek/airconnect:1.9.3
    volumes:
      - ${APPDATA_PATH}/airconnect:/config
    restart: unless-stopped
    env_file: .env
    labels:
      glance.name: AirConnect