services:
  spoolman:
    container_name: spoolman
    image: ghcr.io/donkie/spoolman:latest
    volumes:
      - '${APPDATA_PATH}/spoolman:/home/app/.local/share/spoolman'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.spoolman.tls: true
      traefik.http.routers.spoolman.tls.certresolver: letsencrypt
      traefik.http.routers.spoolman.rule: Host(`${SERVICE_URL}`)
      traefik.http.routers.spoolman.entrypoints: websecure

      glance.name: Spoolman
      glance.icon: sh:spoolman
      glance.url: https://${SERVICE_URL}
      net.unraid.docker.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/spoolman.png
      net.unraid.docker.webui: https://${SERVICE_URL}

networks:
  br0:
    external: true